---
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    labels:
      - 'dependencies'
      - 'npm'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'github-actions'
    directory: '/'
    labels:
      - 'dependencies'
      - 'github_actions'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'docker'
    directory: '/'
    ignore:
      - dependency-name: 'node'
        versions: ['>=25']
    labels:
      - 'dependencies'
      - 'docker'
    schedule:
      interval: 'monthly'
